#ifndef STINTERFACES_GLOBAL_H
#define STINTERFACES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STINTERFACES_LIBRARY)
#  define STINTERFACESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STINTERFACESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STINTERFACES_GLOBAL_H
