/*
Copyright (c) 1996 TST
graphic library for windows

Module Name:
			errors.h

 header file for graphic.dll

 Error codes

*/


#define EM_cooverflow			1
#define EM_coindexerror			2
#define EM_notwindowsbitmap	3
#define EM_referror				4
#define EM_HSP2Derror			5
#define EM_objhandleerror		6
#define EM_filenotfound			7
#define EM_diberror				8
#define EM_outofmemory			9
#define EM_invalidobjecttype	10
#define EM_awakenerror			11
#define EM_invalidstatefile	12
#define EM_versionerror			13
#define EM_metaerror				14
#define EM_metarecord			15
#define EM_fileerror				16
#define EM_abstract				17
#define EM_notrealized			18
#define EM_internal				19
#define EM_nullobjid				20
#define EM_writeerror			21
#define EM_processmetaerror	22
#define EM_triangle				23
#define EM_line					24
#define EM_point					25
#define EM_hglobal				26
#define EM_tobiglinebuffer 	27
#define EM_tomorespaces 		28