
#define raster_START  8192
#define raster_double_start 9200
#define raster_END    9300

#define vector_START  9301
#define vector_END    9402


#define raster_BMP    8192   //
#define raster_TGA    8193
#define raster_JPG    8194   //
#define raster_GIF    8195   //
#define raster_PCX    8196   //
#define raster_LBM    8197
#define raster_TIFF   8198   //
#define raster_RLE    8199
#define raster_PNG    8200

#define raster_DOUBLE 9200
#define raster_ICO    9201

#define vect_VDR      9301
#define vect_MFL      9302
#define vect_WMF      9303


#define video_AVI     9400
#define video_MPG     9401
#define video_FLI     9402
#define video_FLC     9403
#define video_MOV     9404

#define file3d_3DS    9500
#define file_SPACE3D  9501
