#ifndef STVIRTUALMACHINE_GLOBAL_H
#define STVIRTUALMACHINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STVIRTUALMACHINE_LIBRARY)
#  define STVIRTUALMACHINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define STVIRTUALMACHINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STVIRTUALMACHINE_GLOBAL_H
