// Standrd dialog functions
 name "ChoseFolderDialog" arg "STRING","STRING","FLOAT" ret "STRING"   out 99
 name "ChooseFolderDialog" arg "STRING","STRING","FLOAT" ret "STRING"   out 99
 name "FileLoadDialog"   arg "STRING","STRING","STRING" ret "STRING"   out 103
 name "FileSaveDialog"   arg "STRING","STRING","STRING" ret "STRING"   out 102
 name "InputBox"         arg "STRING","STRING","STRING" ret "STRING"   out 159
 name "MessageBox"       arg "STRING","STRING","FLOAT"  ret "FLOAT"    out 160
 name "ChoseColorDialog" arg  "STRING","COLORREF"       ret "COLORREF" out 227
