// Mathematical functions


 name "ln"  arg "FLOAT" ret "FLOAT" out   29
 name "lg"  arg "FLOAT" ret "FLOAT" out   30
 name "log" arg "FLOAT","FLOAT" ret "FLOAT" out 31

 name "exp"  arg "FLOAT" ret "FLOAT" out  33
 name "sqrt" arg "FLOAT" ret "FLOAT" out  34
 name "sqr"  arg "FLOAT" ret "FLOAT" out  35
 name "ed"   arg "FLOAT" ret "FLOAT" out  36
 name "delta" arg "FLOAT" ret "FLOAT" out 37
 name "max" arg "FLOAT","FLOAT" ret "FLOAT" out 38
 name "min" arg "FLOAT","FLOAT" ret "FLOAT" out 39
 name "average" arg "FLOAT","FLOAT" ret "FLOAT" out 40
 name "round" arg "FLOAT","FLOAT" ret "FLOAT" out 41
 name "roundt" arg "FLOAT","FLOAT" ret "FLOAT" out 1129
 name "inc" arg &"FLOAT" out 867
 name "inc" arg &"FLOAT","FLOAT" out 868
 name "dec" arg &"FLOAT" out 869
 name "dec" arg &"FLOAT","FLOAT" out 870
 name "limit" arg "FLOAT","FLOAT","FLOAT" ret "FLOAT" out 871


 name "trunc" arg "FLOAT" ret "FLOAT" out 80
 name "rnd" arg "FLOAT" ret "FLOAT" out 42
 name "and" arg "FLOAT","FLOAT" ret "FLOAT" out 43
 name "or" arg "FLOAT","FLOAT" ret "FLOAT" out 44
 name "not" arg "FLOAT" ret "FLOAT" out 45
 name "abs" arg "FLOAT" ret "FLOAT" out 46
 name "sgn" arg "FLOAT" ret "FLOAT" out 47
 name "rad" arg "FLOAT" ret "FLOAT" out 48
 name "deg" arg "FLOAT" ret "FLOAT" out 49
 name "randomize" arg "FLOAT"  out 177

// Handlers
 
 name "not" arg "HANDLE" ret "FLOAT" out 87
 name "ed"  arg "HANDLE" ret "FLOAT" out 84

// trigonometrical

 name "sin"  arg "FLOAT" ret "FLOAT" out 25
 name "arcsin" arg "FLOAT" ret "FLOAT" out 26
 name "cos"  arg "FLOAT" ret "FLOAT" out 27
 name "arccos" arg "FLOAT" ret "FLOAT" out 28
 name "tan"  arg "FLOAT" ret "FLOAT" out 23
 name "arctan" arg "FLOAT" ret "FLOAT" out 24
