// Matixs functions

 name "MCreate"    arg "FLOAT","FLOAT","FLOAT","FLOAT","FLOAT","FLOAT" ret "FLOAT" out 60
 name "MDelete"    arg "FLOAT","FLOAT" ret "FLOAT" out 61
 name "MFill"      arg "FLOAT","FLOAT","FLOAT" ret "FLOAT" out 62
 name "MGet"       arg "FLOAT","FLOAT","FLOAT","FLOAT" ret "FLOAT" out 63
 name "MPut"       arg "FLOAT","FLOAT","FLOAT","FLOAT","FLOAT" ret "FLOAT" out 64
 name "MEditor"    arg "FLOAT","FLOAT" out 65
 name "MDiag"      arg "FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 66
 name "MAddX"      arg "FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 67
 name "MSubX"      arg "FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 68
 name "MDivX"      arg "FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 69
 name "MMulX"      arg "FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 70
 name "MDet"       arg "FLOAT","FLOAT"  ret "FLOAT" out 71
 name "MDelta"     arg "FLOAT","FLOAT"  ret "FLOAT" out 72
 name "MEd"        arg "FLOAT","FLOAT"  ret "FLOAT" out 73
 name "MTransp"    arg "FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 74
 name "MNot"       arg "FLOAT","FLOAT"  ret "FLOAT" out 76
 name "MSum"       arg "FLOAT","FLOAT"  ret "FLOAT" out 77
 name "MAddC"      arg "FLOAT","FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 75
 name "MSubC"      arg "FLOAT","FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 78
 name "MMulC"      arg "FLOAT","FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 79
 name "MDivC"      arg "FLOAT","FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 90
 name "MMul"       arg "FLOAT","FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 91
 name "MGlue"      arg "FLOAT","FLOAT","FLOAT","FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 92
 name "MCut"       arg "FLOAT","FLOAT","FLOAT","FLOAT","FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 93
 name "MMove"      arg "FLOAT","FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 94
 name "MObr"       arg "FLOAT","FLOAT","FLOAT"  ret "FLOAT" out 95
 name "MSaveAs"    arg "FLOAT","STRING","FLOAT"  ret "FLOAT" out 100
 name "MLoad"      arg "FLOAT","STRING","FLOAT"  ret "FLOAT" out 101
 name "MAddColumn" arg "FLOAT","FLOAT"  ret "FLOAT" out 102
 name "MAddRow"    arg "FLOAT","FLOAT"  ret "FLOAT" out 103
 name "MDim"       arg "FLOAT",&"FLOAT",&"FLOAT",&"FLOAT",&"FLOAT" ret "FLOAT" out 96
 name "MSort"      arg "FLOAT","FLOAT","FLOAT","FLOAT" ret "FLOAT" out 760


