// strings functions
 name "Left" arg "STRING","FLOAT" ret "STRING" out 125
 name "Right" arg "STRING","FLOAT" ret "STRING" out 126
 name "Substr" arg "STRING","FLOAT","FLOAT" ret "STRING" out 127
 name "Substr" arg "STRING","FLOAT" ret "STRING" out 779
 name "Pos" arg "STRING","STRING","FLOAT" ret "FLOAT" out 128
 name "Replicate" arg "STRING","FLOAT" ret "STRING" out 129
 name "Lower" arg "STRING" ret "STRING" out 130
 name "Upper" arg "STRING" ret "STRING" out 131
 name "Ansi_To_Oem" arg "STRING" ret "STRING" out 132
 name "Oem_To_Ansi" arg "STRING" ret "STRING" out 133
 name "Compare" arg "STRING","STRING" ret "FLOAT" out 134
 name "Comparei" arg "STRING","STRING","FLOAT" ret "FLOAT" out 135
 name "Length" arg "STRING" ret "FLOAT" out 136
 name "Ltrim" arg "STRING" ret "STRING" out 137
 name "Rtrim" arg "STRING" ret "STRING" out 138
 name "Alltrim" arg "STRING" ret "STRING" out 139
 name "ASCII" arg "STRING" ret "FLOAT" out 140
 name "Chr" arg "FLOAT" ret "STRING" out 141
 name "String" arg "FLOAT" ret "STRING" out 142
// name "StringEx" arg "FLOAT","STRING" ret "STRING" out 114
 name "Float" arg "STRING" ret "FLOAT" out 143
 name "Change" arg "STRING","STRING","STRING" ret "STRING" out 119
