Main Idea Oleg Moukhin

Programming:
2d/3d Graphics - Alexander Shelemekhov
IDE            - Alexander Shelemekhov
Compiler       - Vlad Noscov
Equ            - Vlad Noscov
Online Help    - Vlad Noscov
System library - Vlad Noscov
Bitmap editor  - Andrey Kolchanov
Syntax editor  - Alexey Shelemekhov
Network        - Alexander Shelemekhov
Database       - Alexander Shelemekhov / Andrey Kolchanov
Art            - Vlad Noscov/Alexander Shelemekhov


Graphics filters:
gif - Alexey Shelemekhov
pcx - Alexey Shelemekhov
tga - Alexey Shelemekhov
jpg - Alexey Shelemekhov
rle - Alexey Shelemekhov
wmf - Alexey/Alexander Shelemekhov
3ds - Alexander Shelemekhov

Tester - Oleg Moukhin
