/****************************************************************/
//This file auto generated by BuildGen.Exe
// 19.2000.6
#define __SC_RELEASE__  3,3
#define __SC_RELEASEstr__  "3.3"
#define __SC_BUILD__  1572
#define __SC_BUILDstr__  "1572"
#define __YEAR__  "1996-2012"
/****************************************************************/
